 -- insert into students (first_name, last_name, birth_date)values
 -- ('Marc','Benichou','1998-11-02'),
 -- ('Yoan','Cohen','2010-12-03'),
 -- ('Lea','Benichou','1987-07-27'),
  -- ('Amelia','Dux','1996-04-07'),
  -- ('David','Grez','2003-06-14'),
  -- ('Omer','Simpson','1980-10-03')
 --insert into students (first_name, last_name, birth_date)values
-- ('Nadya','Babenko','1994-08-07')
-- select * from students; 
-- select  first_name, last_name from students;
-- select  first_name, last_name from students where id=2;
-- select  first_name, last_name from students where last_name= 'Benichou'and first_name = 'Marc';
 --select  first_name, last_name from students where last_name= 'Benichou' OR  first_name = 'Marc'
-- select  first_name, last_name from students where  first_name    LIKE '%a%';
--select  first_name, last_name from students where  first_name    LIKE 'a%';
--select  first_name, last_name from students where  first_name    ILIKE 'a%';
--select  first_name, last_name from students where ( right(first_name, 2)    LIKE 'a%') 
--select  first_name, last_name from students where id =  1 and id = 3 ;
select  * from students where birth_date >=  '2000-01-1' ;

