POST http://localhost:3000/register
Content-Type: application/json

"first", "last", "email", "username", "password" 
{
"first": "Nadya",
"last": "Babenko",
"email": "nadine.babenko@gmail.com",
"username": "nadinebabenko",
"password": "goodbye1"
}